### ISSUE TITLE
Sort descending / ascending wrong icon arrow direction

### ISSUE THREAD

**Issue by somebee** [phosphor-icons/core#13] opened 2023-12-19 11:01 UTC
<img width="461" alt="image" src="https://github.com/phosphor-icons/core/assets/8467/57230877-1417-4c9b-9d7d-29dc93abfbf7">

This seems like a bug? Sort descending should clearly point down, and ascending should point up.

**Comment by rektdeckard** [comment] 2023-12-19 22:29
You would think so, but this does seem to be the de-facto standard. The arrow points in the direction in which the sort value is increasing. For example, in Ascending order, values increase as you go *down* the list.

**Comment by rektdeckard** [comment] 2023-12-19 22:30
Closing because this is intended behavior.

**Closed** 2023-12-19 22:30 UTC

**Comment by somebee** [comment] 2023-12-22 12:40
On mac, descending is arrow down, and ascending is arrow up.
<img width="202" alt="image" src="https://github.com/phosphor-icons/core/assets/8467/c93b2014-4068-4269-b9db-14155cad184d">
